### ISSUE TITLE
Request for visualization demo

### ISSUE THREAD

**Issue by HaoqianSong** [alexandre-eymael/CropMAE#1]
Is there a visualization demo for image occlusion recovery? Want to see the image recovery effect of the model with high masked-up.

**Comment by rvandeghen** [comment]
Hi @HaoqianSong.

Are you interested in a code/notebook to visualize the reconstruction of masked patches, as we do during training or is it something else ?

Renaud

**Comment by HaoqianSong** [comment]
Not for training, for interactive visualization demo, like  https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb

**Comment by alexandre-eymael** [comment]
Hi @HaoqianSong,

Sorry for the delay.

We have just updated the repository with a demonstration tool. You can run an interactive demo of CropMAE in the cloud using [Colab Notebooks](https://colab.research.google.com/drive/173wOiSf0ViXgTd6ARibVn1E6pN_asJKk), or locally with the [Notebook Demo](https://github.com/alexandre-eymael/CropMAE/blob/main/cropmae_reconstructions.ipynb).

Please don't hesitate to ask if you need anything else!
