### ISSUE TITLE
is norm pixel loss matter in visualization?

### ISSUE THREAD

**Issue by SeongjuLee** [alexandre-eymael/CropMAE#11]
Thanks for sharing your valuable work!
We try to reproduce your work and the visualization result at 200 epoch looks strange as following image.
![image](https://github.com/user-attachments/assets/f70a750f-8c19-4aa8-bf5c-61897db6f7c7)

Note that the weight downloaded from your google drive works well.
In order to obtain visualization result, should i turn off the norm pixel loss?

**Comment by alexandre-eymael** [comment]
Hi @SeongjuLee,

Thank you for your message.

Indeed, with the default parameters, the model is trained to predict the **normalized** pixel values of each masked patch, as this has been shown to improve the learned features for downstream tasks (refer to [the MAE paper](https://arxiv.org/abs/2111.06377)).

If you want a human-friendly reconstruction (at the cost of some performance), you will need to turn this parameter off.
