### ISSUE TITLE
Question for image task

### ISSUE THREAD

**Issue by c7878783** [alexandre-eymael/CropMAE#3]
Hello, this paper has been very inspiring to me, but I have a question. Have you tried using your method on downstream image tasks such as supervised identification, object detection, and segmentation?Besides, I think that pre-training using the ImageNet1K dataset might yield even better performance. Have you attempted this approach?

**Comment by alexandre-eymael** [comment]
Hello @c7878783,

Thank you for your question.

We did not spend much time trying different downstream tasks, as it requires large computational resources. However, our method was not designed to perform well in such tasks, as our extremely high masking ratio and the Siamese architecture likely prevent the network from learning any conceptual understanding of the visual world, unlike other MAE methods. The attention maps in Fig. 5 suggest that our model might perform well on non-propagation tasks that benefit from boundary detection, such as object detection and segmentation, but that would likely require adaptation.

For ImageNet1K, we mainly kept a small dataset size to be comparable with other methods (e.g., SiamMAE), as they mainly train on video datasets. The scalability of our method on larger datasets might be the subject of future work.

If you are interested in improving our model for other tasks, or experimenting and improving its scalability, feel free to reach out to us by email to continue the discussion!
